tag: dev

reverse-proxy:
  replicaCount: 1
  image: nginx

api:
  replicaCount: 1
  image: okteto.dev/api

frontend:
  replicaCount: 1
  image: okteto.dev/frontend

mongodb:
  password: "Password!1@2"
