apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    {{- include "movies.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: load-data
          image: {{ .Values.api.image }}:{{ .Values.tag }}
          command:
            - yarn
            - load
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
      containers:
        - name: api
          image: {{ .Values.api.image }}:{{ .Values.tag }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: mongodb-password
            - name: MONGODB_USERNAME
              value: okteto
            - name: MONGODB_DATABASE
              value: okteto
            - name: MONGODB_HOST
              value: mongodb
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /api/healthz
              port: 8080
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /api/healthz
              port: 8080
