on:
  push:
    branches:
      - main

name: Build to Okteto Global Registry
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: Build
        uses: okteto/build@main
        with:
          global: true
        env:
          OKTETO_GIT_COMMIT: ${{ github.sha }}